name: Build and Deploy

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'
  workflow_dispatch: 

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      CHROME_BIN: chromium

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install chrome for WASM tests
      uses: browser-actions/setup-chrome@v1

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Gradle clean
      run: ./gradlew clean 
    
    - name: Run tests with Gradle
      run: ./gradlew allTests

    - name: Update Yarn Store
      run: ./gradlew kotlinUpgradeYarnLock

    - name: Build
      run: ./gradlew build -x allTests --info

    - name: Store wasm files
      uses: actions/upload-artifact@master
      with:
        name: wasm-files
        path: ./build/js/packages/KoNLLU-Viewer-wasm/kotlin/*
        retention-days: 1

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: ./frontend/conllu-viewer

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Collect artifacts
      uses: actions/download-artifact@master
      with:
        name: wasm-files
        path: ./tmp/
    
    - run: ls -alh ./tmp/
    
    - name: Copy and lst imported files
      run: |
        cp ./tmp/* ./public/

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build project
      run: yarn build

    # # Deploy to GitHub Pages
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./frontend/build  # Replace with your frontend build directory
